-- Run in Supabase SQL Editor. Categories are illustrative; edit before launch.
create extension if not exists pgcrypto;
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text not null unique check(length(username) between 3 and 30), is_commissioner boolean not null default false, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, description text not null default '', active boolean not null default true);
create table public.weeks (id date primary key, lock_at timestamptz not null, season_start date not null);
create table public.picks (user_id uuid not null references public.profiles(id) on delete cascade, week_id date not null references public.weeks(id), category_id uuid not null references public.categories(id), points integer not null check(points between 0 and 25), primary key(user_id,week_id,category_id));
create table public.events (id uuid primary key default gen_random_uuid(), week_id date not null references public.weeks(id), category_id uuid not null references public.categories(id), occurred_at timestamptz not null, quantity integer not null check(quantity between 1 and 100), note text not null default '', created_by uuid not null references public.profiles(id), created_at timestamptz not null default now());
create index events_week_category on public.events(week_id,category_id);
create index picks_week_user on public.picks(week_id,user_id);
create or replace function public.new_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,username) values(new.id,'player_'||replace(new.id::text,'-','')); return new; end $$;
create trigger create_profile after insert on auth.users for each row execute function public.new_profile();
create or replace function public.is_commissioner() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and is_commissioner)$$;
create or replace function public.validate_lineup() returns trigger language plpgsql as $$ declare total integer; n integer; active_n integer; lock_time timestamptz; begin select lock_at into lock_time from public.weeks where id=new.week_id; if now()>=lock_time then raise exception 'Lineup locked'; end if; if not exists(select 1 from public.categories where id=new.category_id and active) then raise exception 'Inactive category'; end if; select coalesce(sum(points),0),count(*) into total,n from public.picks where user_id=new.user_id and week_id=new.week_id; select count(*) into active_n from public.categories where active; if n<>active_n or total<>100 then raise exception 'Lineup must allocate exactly 100 points across all active categories'; end if; return null; end $$;
-- Lineup validation is performed atomically by the submit_lineup function below.
create or replace function public.submit_lineup(p_week date,p_picks jsonb) returns void language plpgsql security definer set search_path=public as $$ declare lock_time timestamptz; active_n integer; input_n integer; total integer; begin if auth.uid() is null then raise exception 'Login required'; end if; select lock_at into lock_time from weeks where id=p_week for update; if lock_time is null or now()>=lock_time then raise exception 'Lineup is locked or week is missing'; end if; if jsonb_typeof(p_picks)<>'array' then raise exception 'Invalid lineup'; end if; select count(*) into active_n from categories where active; select count(*),coalesce(sum((x->>'points')::integer),0) into input_n,total from jsonb_array_elements(p_picks) x; if input_n<>active_n or total<>100 or exists(select 1 from jsonb_array_elements(p_picks) x where (x->>'points')::integer not between 0 and 25) or (select count(distinct x->>'category_id') from jsonb_array_elements(p_picks) x)<>active_n or exists(select 1 from jsonb_array_elements(p_picks) x left join categories c on c.id=(x->>'category_id')::uuid and c.active where c.id is null) then raise exception 'Invalid 100-point lineup'; end if; delete from picks where user_id=auth.uid() and week_id=p_week; insert into picks(user_id,week_id,category_id,points) select auth.uid(),p_week,(x->>'category_id')::uuid,(x->>'points')::integer from jsonb_array_elements(p_picks) x; end $$;
create or replace view public.weekly_scores with (security_invoker=true) as select p.week_id,p.user_id,pr.username,coalesce(sum(p.points*coalesce(e.quantity,0)),0)::bigint as score from picks p join profiles pr on pr.id=p.user_id left join (select week_id,category_id,sum(quantity) quantity from events group by week_id,category_id)e on e.week_id=p.week_id and e.category_id=p.category_id group by p.week_id,p.user_id,pr.username;
create or replace view public.season_scores with (security_invoker=true) as select w.season_start,s.user_id,s.username,sum(s.score)::bigint score from weekly_scores s join weeks w on w.id=s.week_id group by w.season_start,s.user_id,s.username;
alter table profiles enable row level security; alter table categories enable row level security; alter table weeks enable row level security; alter table picks enable row level security; alter table events enable row level security;
create policy profiles_read on profiles for select to authenticated using(true);
create policy profiles_update on profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid() and is_commissioner=false);
-- Commissioner profiles are granted manually in SQL; no client can grant itself commissioner status.
create policy categories_read on categories for select to authenticated using(true);
create policy categories_admin on categories for all to authenticated using(is_commissioner()) with check(is_commissioner());
create policy weeks_read on weeks for select to authenticated using(true);
create policy weeks_admin on weeks for all to authenticated using(is_commissioner()) with check(is_commissioner());
create policy picks_read on picks for select to authenticated using(true);
create policy events_read on events for select to authenticated using(true);
create policy events_admin on events for all to authenticated using(is_commissioner()) with check(is_commissioner());
grant execute on function public.submit_lineup(date,jsonb) to authenticated;
insert into categories(name,description) values ('Pittsburgh Scanner','A distinct qualifying scanner story'),('Florida Story','A distinct Florida news story'),('Steelers Talk','A distinct Steelers discussion segment'),('Facebook Comments','A distinct set of local Facebook comments read on air'),('Bob’s Shorts','A distinct mention of Bob’s shorts'),('Listener Talkback','A distinct listener talkback played on air') on conflict(name) do nothing;
