-- Run in Supabase SQL Editor. Categories are illustrative; edit before launch.
create extension if not exists pgcrypto;
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text not null unique check(length(username) between 3 and 30), is_commissioner boolean not null default false, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, description text not null default '', active boolean not null default true, scoring_type text not null default 'allocation' check(scoring_type in ('allocation','closest_guess')), display_order integer not null default 0);
create table public.weeks (id date primary key, lock_at timestamptz not null, season_start date not null);
create table public.picks (user_id uuid not null references public.profiles(id) on delete cascade, week_id date not null references public.weeks(id), category_id uuid not null references public.categories(id), points integer not null check(points between 0 and 25), primary key(user_id,week_id,category_id));
create table public.birthday_predictions (user_id uuid not null references public.profiles(id) on delete cascade, week_id date not null references public.weeks(id) on delete cascade, guess integer not null check(guess between 0 and 500), primary key(user_id,week_id));
create table public.events (id uuid primary key default gen_random_uuid(), week_id date not null references public.weeks(id), category_id uuid not null references public.categories(id), occurred_at timestamptz not null, quantity integer not null check(quantity between 1 and 100), note text not null default '', created_by uuid not null references public.profiles(id), created_at timestamptz not null default now());
create index events_week_category on public.events(week_id,category_id);
create index picks_week_user on public.picks(week_id,user_id);
create or replace function public.new_profile() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,username) values(new.id,'player_'||left(replace(new.id::text,'-',''),20)); return new; end $$;
revoke all on function public.new_profile() from public,anon,authenticated;
create trigger create_profile after insert on auth.users for each row execute function public.new_profile();
create or replace function public.is_commissioner() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and is_commissioner)$$;
revoke all on function public.is_commissioner() from public,anon;
grant execute on function public.is_commissioner() to authenticated;
-- Lineup validation is performed atomically by the submit_lineup function below.
create or replace function public.submit_lineup(p_week date,p_picks jsonb,p_birthday_guess integer) returns void language plpgsql security definer set search_path='' as $$ declare lock_time timestamptz; active_n integer; input_n integer; total integer; begin if auth.uid() is null then raise exception 'Login required'; end if; select lock_at into lock_time from public.weeks where id=p_week for update; if lock_time is null or now()>=lock_time then raise exception 'Lineup is locked or week is missing'; end if; if jsonb_typeof(p_picks)<>'array' or p_birthday_guess not between 0 and 500 then raise exception 'Invalid lineup'; end if; select count(*) into active_n from public.categories where active and scoring_type='allocation'; select count(*),coalesce(sum((x->>'points')::integer),0) into input_n,total from jsonb_array_elements(p_picks) x; if input_n<>active_n or total<>100 or exists(select 1 from jsonb_array_elements(p_picks) x where (x->>'points')::integer not between 0 and 25) or (select count(distinct x->>'category_id') from jsonb_array_elements(p_picks) x)<>active_n or exists(select 1 from jsonb_array_elements(p_picks) x left join public.categories c on c.id=(x->>'category_id')::uuid and c.active and c.scoring_type='allocation' where c.id is null) then raise exception 'Invalid 100-point lineup'; end if; delete from public.picks where user_id=auth.uid() and week_id=p_week; insert into public.picks(user_id,week_id,category_id,points) select auth.uid(),p_week,(x->>'category_id')::uuid,(x->>'points')::integer from jsonb_array_elements(p_picks) x; insert into public.birthday_predictions(user_id,week_id,guess) values(auth.uid(),p_week,p_birthday_guess) on conflict(user_id,week_id) do update set guess=excluded.guess; end $$;
create or replace view public.weekly_scores with (security_invoker=true) as with base as (select p.week_id,p.user_id,pr.username,coalesce(sum(p.points*coalesce(e.quantity,0)),0)::bigint as base_score from picks p join profiles pr on pr.id=p.user_id join categories pc on pc.id=p.category_id and pc.scoring_type='allocation' left join (select week_id,category_id,sum(quantity) quantity from events group by week_id,category_id)e on e.week_id=p.week_id and e.category_id=p.category_id group by p.week_id,p.user_id,pr.username), birthday_actual as (select e.week_id,coalesce(sum(e.quantity),0)::integer actual from events e join categories c on c.id=e.category_id where c.scoring_type='closest_guess' group by e.week_id) select b.week_id,b.user_id,b.username,(b.base_score+case when bp.guess is null then 0 else greatest(0,50-abs(bp.guess-coalesce(ba.actual,0))*5) end)::bigint score from base b left join birthday_predictions bp on bp.week_id=b.week_id and bp.user_id=b.user_id left join birthday_actual ba on ba.week_id=b.week_id;
create or replace view public.season_scores with (security_invoker=true) as select w.season_start,s.user_id,s.username,sum(s.score)::bigint score from weekly_scores s join weeks w on w.id=s.week_id group by w.season_start,s.user_id,s.username;
alter table profiles enable row level security; alter table categories enable row level security; alter table weeks enable row level security; alter table picks enable row level security; alter table birthday_predictions enable row level security; alter table events enable row level security;
create policy profiles_read on profiles for select to authenticated using(true);
create policy profiles_update on profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid() and is_commissioner=false);
-- Commissioner profiles are granted manually in SQL; no client can grant itself commissioner status.
create policy categories_read on categories for select to authenticated using(true);
create policy categories_admin on categories for all to authenticated using(is_commissioner()) with check(is_commissioner());
create policy weeks_read on weeks for select to authenticated using(true);
create policy weeks_admin on weeks for all to authenticated using(is_commissioner()) with check(is_commissioner());
create policy picks_read on picks for select to authenticated using(true);
create policy birthday_predictions_read on birthday_predictions for select to authenticated using(true);
create policy events_read on events for select to authenticated using(true);
create policy events_admin on events for all to authenticated using(is_commissioner()) with check(is_commissioner());
revoke all on function public.submit_lineup(date,jsonb,integer) from public,anon;
grant execute on function public.submit_lineup(date,jsonb,integer) to authenticated;
insert into categories(name,description,scoring_type,display_order) values ('Pittsburgh Scanner','A distinct qualifying scanner story','allocation',10),('A Florida story involving nudity','A distinct Florida story involving nudity','allocation',20),('Over 15 Mike McCarthy Meows in One Interview Clip','A qualifying interview clip containing more than 15 Mike McCarthy meows','allocation',30),('Something or someone sent to Tha’ Crossroads','A distinct instance of something or someone being sent to Tha’ Crossroads','allocation',40),('Listener Talkback','A distinct listener talkback played on air','allocation',50),('🎂 Bob’s Birthday Wishes 🎂','Guess how many times Bob will be wished a Happy Birthday this week.','closest_guess',60) on conflict(name) do nothing;
